### ISSUE TITLE
Access statistics via js web

### ISSUE THREAD

**Issue by timleers** [pirsch-analytics/pirsch-js-sdk#11]
we are currently trying to add some basic statistics within our vue application. 

as far as i see this is currently not possible with the new version 2 because pirsch-sdk/web-api can only be initialized with `PirschTokenClientConfig` and Access Tokens cant have read access to statistics. Is that correct?

we then tried out version v1.4.1. were i was able to request the domain. but the API response is `null`. i think thats because the request is not authenticated. at least when i did a simple cURL the response was the same. there is also no bearer set or any cookie in the request header.
```
  const client = new Client({
    hostname: "<domain>",
    clientID: "<client_id>",
    clientSecret: "<client_secret>",
    protocol: "https"
  })
  
  const domains = await client.domain();
```
should this work in general when calling it from a frontend? or does it also only work for node?

thanks in advance for any help 🙏

**Comment by Kugelschieber** [comment]
Hi Tim,

access tokens are write-only, so you're right. To read statistics you need to use the PirschNodeApiClient, which shouldn't be used on the client side because it requires a client ID and secret.

> but the API response is null. i think thats because the request is not authenticated.

That's odd. We return errors in the body, so it shouldn't be null, unless there is no data. What HTTP status code did you receive?

> should this work in general when calling it from a frontend? or does it also only work for node?

Hmm, I think it should work as we use axios, but as I said I wouldn't recommend using it inside the browser. The best option, and this is also how a few of our customers solve it, is to use it on your backend. There is also a Go and PHP SDK, if you prefer that.

I also recommend testing out the API using Postman or something similar. It's really easy to use: https://docs.pirsch.io/api-sdks/api/

I hope this helps! Let me know if you need more help or have other questions :)

**Comment by timleers** [comment]
thank you for the quick answer. 

We can make use of the ruby client but thats a bit of extra work. But i see the point, from security perspective it might be dangerous to expose the secret. In our case it would be ok because the secret has only access to statistics and only authorized internal users are receiving the secret because its not bundled in the javascript code.

> That's odd. We return errors in the body, so it shouldn't be null, unless there is no data. What HTTP status code did you receive?

The status code of the unauthorized requests for domains was 200.

I will close the issue because we will use the ruby sdk for now. Thank you for your support!

**Comment by Kugelschieber** [comment]
> The status code of the unauthorized requests for domains was 200.

Thank you for letting me know :) I'll look into it.
